import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import MainHeader from "@/components/main/MainHeader";
import { QueryClientProvider } from "@tanstack/react-query";
import { queryClient } from "@/components/util/http";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "NextLevel Food",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <QueryClientProvider client={queryClient}>
      <body className="bg-gray-900">
        <MainHeader />
        {children}
      </body>
      </QueryClientProvider>
    </html>
  );
}
